# Generated by Django 3.2.16 on 2023-02-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='nota',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pending',
            field=models.BooleanField(default=True, verbose_name='Pendiente'),
        ),
    ]
