# Generated by Django 3.2.16 on 2023-02-05 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('warehome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehomedetail',
            name='attribut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.attribut', verbose_name='Atributo'),
            preserve_default=False,
        ),
    ]
