# Generated by Django 3.2.16 on 2023-02-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehome', '0002_warehomedetail_attribut'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehomedetail',
            name='description',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Descripción'),
        ),
    ]
