# Generated by Django 3.2.16 on 2023-02-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('warehome', '0003_warehomedetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='attribut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.attribut', verbose_name='Atributo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Descripción'),
        ),
    ]
