# Generated by Django 3.2.16 on 2023-02-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230209_0029'),
        ('warehome', '0004_auto_20230204_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehomedetail',
            name='attribut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.attribut', verbose_name='Atributo'),
        ),
    ]
