# Generated by Django 3.2.16 on 2023-02-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230209_0029'),
        ('warehome', '0005_alter_warehomedetail_attribut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehomedetail',
            name='attribut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.attribut', verbose_name='Atributo'),
            preserve_default=False,
        ),
    ]
