# Generated by Django 3.2.16 on 2023-03-06 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20230306_0257'),
        ('warehome', '0006_alter_warehomedetail_attribut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductout',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicalproductout',
            name='number',
            field=models.BigIntegerField(blank=True, db_index=True, verbose_name='Documento No.'),
        ),
        migrations.AlterField(
            model_name='historicalproductout',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, default='P1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehome.documentout', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='productout',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='productout',
            name='number',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Documento No.'),
        ),
        migrations.AlterField(
            model_name='productout',
            name='type',
            field=models.ForeignKey(default='P1', on_delete=django.db.models.deletion.CASCADE, to='warehome.documentout', verbose_name='Tipo'),
        ),
    ]
