# Generated by Django 3.2.16 on 2023-03-06 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehome', '0007_auto_20230306_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductout',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productout',
            name='customer',
        ),
        migrations.AddField(
            model_name='historicalproductout',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='productout',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
