# Generated by Django 3.2.16 on 2023-04-04 09:29

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('paid_until', models.DateField()),
                ('on_trial', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_n', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='No. Documento')),
                ('tipo', models.CharField(choices=[('CEDULA', 'C.C'), ('TARGETA DE IDENTIDAD', 'T.I'), ('NIT', 'Nit')], default='Auto', max_length=20, verbose_name='Tipo de documento')),
                ('email', models.CharField(blank='True', max_length=150, null='True', verbose_name='Correo electrónico')),
                ('company', models.CharField(max_length=100, verbose_name='Razon social')),
                ('address', models.CharField(blank='True', max_length=100, null='True', verbose_name='Dirección')),
                ('phone', models.CharField(blank='True', max_length=100, null='True', verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='customers.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
