# Generated by Django 3.2.16 on 2023-01-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_n', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Nit')),
                ('company', models.CharField(max_length=100, verbose_name='Razon social')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
            },
        ),
    ]
