# Generated by Django 3.2.16 on 2023-03-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank='True', max_length=100, null='True', verbose_name='Dirección'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-03-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank='True', max_length=150, null='True', verbose_name='Correo electrónico'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank='True', max_length=100, null='True', verbose_name='Teléfono'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='customer',
            name='tipo',
            field=models.CharField(choices=[('CEDULA', 'C.C'), ('TARGETA DE IDENTIDAD', 'T.I'), ('NIT', 'Nit'), ('AUTO', 'Auto')], default='Auto', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_n',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Nit'),
        ),
    ]
