# Generated by Django 3.2.16 on 2023-03-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20230306_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_n',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nit'),
        ),
    ]
