# Generated by Django 3.2.16 on 2023-03-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_id_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_n',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='No. Documento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tipo',
            field=models.CharField(choices=[('CEDULA', 'C.C'), ('TARGETA DE IDENTIDAD', 'T.I'), ('NIT', 'Nit')], default='Auto', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
