# Generated by Django 3.2.16 on 2023-02-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20230228_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
