# Generated by Django 3.2.16 on 2023-02-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0004_auto_20230228_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregdo'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado'), ('DEVUELTO', 'Devuelto')], default='Pendiente', max_length=10),
        ),
    ]
