# Generated by Django 3.2.16 on 2023-02-05 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('image', models.ImageField(blank=True, upload_to='photos/categories', verbose_name='Imagen')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('codigo', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Código')),
                ('barra', models.CharField(max_length=200, unique=True, verbose_name='Barra')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('name_extend', models.CharField(max_length=200, unique=True, verbose_name='Nombre Extendido')),
                ('images', models.ImageField(upload_to='photos/products')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Url')),
                ('description', models.TextField(blank=True, max_length=4000, verbose_name='Detalle')),
                ('price1', models.PositiveSmallIntegerField(verbose_name='Precio1')),
                ('price2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio2')),
                ('price3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio3')),
                ('price4', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio4')),
                ('price5', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio5')),
                ('price_old', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio Anterior')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('codigo', models.CharField(db_index=True, max_length=40, verbose_name='Código')),
                ('barra', models.CharField(db_index=True, max_length=200, verbose_name='Barra')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('name_extend', models.CharField(db_index=True, max_length=200, verbose_name='Nombre Extendido')),
                ('images', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=200, verbose_name='Url')),
                ('description', models.TextField(blank=True, max_length=4000, verbose_name='Detalle')),
                ('price1', models.PositiveSmallIntegerField(verbose_name='Precio1')),
                ('price2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio2')),
                ('price3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio3')),
                ('price4', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio4')),
                ('price5', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio5')),
                ('price_old', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio Anterior')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Modificado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Producto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, verbose_name='Url')),
                ('image', models.TextField(blank=True, max_length=100, verbose_name='Imagen')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Modificado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Categoria',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAttribut',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Atributo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products', verbose_name='Imagenes')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Galeria de Imagenes',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Categoría')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Categoria de Producto',
                'verbose_name_plural': 'Categoria de Productos',
            },
        ),
    ]
