# Generated by Django 3.2.16 on 2023-02-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='Oferta'),
        ),
    ]
